---
- name: restart snmpd
  service:
    name : snmpd
    state: restarted
  when:
    - ansible_virtualization_type == "docker" or
        ansible_virtualization_type == "podman" or
        ansible_virtualization_type == "container"
