---
- name: Set resolv_conf_file if running in Docker
  ansible.builtin.set_fact:
    __resolv_conf_file: "{{ __resolv_conf_file_docker }}"
  when:
    - ansible_virtualization_type | regex_search("docker|podman|container")


- name: Deploy {{ __resolv_conf_file }}
  ansible.builtin.template:
    src: templates/resolv_conf.j2
    dest: "{{ __resolv_conf_file }}"
    mode: "0644"


...
