---
- name: Set resolv_conf_file if running in Docker
  set_fact:
    __resolv_conf_file: "{{ __resolv_conf_file_docker }}"
  when: ansible_virtualization_type == "docker"


- name: Deploy {{ __resolv_conf_file }}
  template:
    src: templates/resolv_conf.j2
    dest: "{{ __resolv_conf_file }}"
    mode: 0644


...
