---
- name: Include distribution specific variables or include defaults
  block:
    - name: Include distribution specific variables
      include_vars:
        file: "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}.yml"

  rescue:
    - name: Non-supported distribution; using default package set
      include_vars:
        file: __default_packages.yml


- name: Install package set
  package:
    name  : "{{ __base_packages }}"
    state : present


...
